language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Qx6vu32wBkdSt2r/w0C5mXvkzVJlS2XQnxZ9Gl+tzijBtIHb8Az4JC3Vhf5Z8pvHu2gC7AmjsfiFYH1fDa66g9eLVfpnSIg6q8Xw295z4jQFiJYVWE70yb1c8eVEu20yTYbFgNx30Yqs1uwbXu+7/7Mzlvqcmiw0v5yYF8VwHx+wbead64Ev9wXvQAsBnVXb7R+Iql75At7jpZvQ28rx0fLwNpKli3R7Wss1atgdRa2uwdbeIWpgNzVKgOPhlkFohZNQynjAPpCm8RKD24Mqv1BXXUXgJjMS0fSz8T85Vg5eElBogsx/ywT1cih4n+/XtE1bWRysDeBw6PpYh5lTrEeJmJjkkzjKGfQlG6c0Pi80Edda0Pz8ZDS3q+8kKrS/0ejszvl3HSfyBb+0xDeIkDOQHIV/LoDdIlHhpX0asPNMtjjsIpPye0X8gDsI3mmQEYPGMDjP2Xo/QWaO/ypFmiTPXC2QLQG8RuWF2jL7rjT7tdNnSqj/fTx+WPyhVFNxenxJLHsmM/Gax9IqIbIWZf4q+gasFoWY4t83hbw5iA5rPHeJY6veRM4Ilby7I8Y4Btci2SFm4WrbW5VvJ14t046lVvCme3sBgusB0SCdZgFK12MGvAwPrHZHxJRhUIykV3M2iCMGik6FHEEvaZpzfYFLRM1zEhTKR1d8bfm2zFM=
  file:
    - "hast-util-find-and-replace.js"
    - "hast-util-find-and-replace.min.js"
  on:
    tags: true
    node: '9.0'
